### ISSUE TITLE
Usage on OSX?

### ISSUE THREAD

**Issue by Saeven** [ekenberg/quotatool#21]
Hello!  Thank you for the time you have put into this library.

I've downloaded/installed via brew, and have read the README, but try as I might nothing seems to work.  I'm trying to set a limit on /Users/foo

```
quotatool -u foo -b -q 10G -l 12G /System/Volumes/Data/Users/foo
```

and

```
quotatool -u foo -b -q 10G -l 12G /Users/foo
```

both yield:

quotatool: Filesystem /Users/foo does not exist.  

Similarly, invoking on any device listed in `diskutil list` yields the same error.  Have I overlooked a detail?

Am on Big Sur, 11.3

Thanks for your guidance!

**Comment by ekenberg** [comment]
I am embarrassed to comment on this after over two years left unanswered. However - it seems to me the error messages tells you what you need to know: you are trying to set disk quota limits on a filesystem that does not exist? When trying to set quotas on an existing filesystem, have you made sure that disk quota is enabled and working before using quotatool? 

Does this help? https://apple.stackexchange.com/questions/419845/how-to-setup-disk-quotas-on-macos-big-sur

I do not currently have access to a machine with Big Sur so it's hard for me to reproduce the issue.
