### ISSUE TITLE
Implicit declaration error on MacOS Sonoma

### ISSUE THREAD

**Issue by Moisan** [ekenberg/quotatool#24]
When trying to build quotatool on MacOS Sonoma, I get this error within the `make install` step:

```
clang -g -O2  -I./src -I./src/darwin -DHAVE_CONFIG_H  -c -o src/darwin/quota.o src/darwin/quota.c
src/main.c:211:17: error: call to undeclared function 'quota_reset_grace'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          if (! quota_reset_grace(quota, (argdata->block_reset ? GRACE_BLOCK : GRACE_INODE)))
                ^
src/main.c:211:17: note: did you mean 'xfs_reset_grace'?
./src/quota.h:113:13: note: 'xfs_reset_grace' declared here
int         xfs_reset_grace(quota_t *myquota, int grace_type);
            ^
1 error generated.
make: *** [src/main.o] Error 1
```

Adding `-Wno-implicit-function-declaration` to `CFLAGS` is a workaround for now.

**Comment by ekenberg** [comment]
Thank you Moisan - I do not have access to MacOS Sonoma so I am grateful for your report. Do you by any chance have a suggestion or even a pull request for a more permanent fix? It would be much appreciated since I cannot really try things out myself at this point.

**Comment by Moisan** [comment]
I think this [commit](https://github.com/ekenberg/quotatool/commit/ad6944baaa73cf6230f9a2bef2399b31c2130547) fixes the issue but is not part of any tag or release. 

A bit more context: the issue was found while packaging `quotatool` with Homebrew. The package needs to point to a release or tag so we are currently using tag `1.6.2`. Simply cutting a new tag or release should be enough to fix this issue.

**Comment by ekenberg** [comment]
Thank you @Moisan, very helpful. I've added tag 1.6.3. Would you mind testing and checking back here?

**Comment by Moisan** [comment]
It does fix the implicit declaration issue but the `install` makefile target now fails:
```
/usr/bin/install -c -D ./quotatool /usr/local/Cellar/quotatool/1.6.3/sbin/quotatool
/usr/bin/install: illegal option -- D
```

I believe it should be something like this to support macOS:
```
install: $(prog)
    $(NORMAL_INSTALL)
    mkdir -p $(DESTDIR)$(sbindir)
    $(INSTALL_PROGRAM) $(srcdir)/$(prog) $(DESTDIR)$(sbindir)/$(prog)
    $(foreach man,$(men),mkdir -p $(DESTDIR)$(mandir)/man$(subst .,,$(suffix $(man))); $(INSTALL_DATA) $(man) $(DESTDIR)$(mandir)/man$(subst .,,$(suffix $(man)))/$(notdir $(man));)
```

**Comment by Moisan** [comment]
Good point, that works! I opened a PR in `homebrew-core` to upgrade `quotatool` with those changes.

**Comment by ekenberg** [comment]
> Good point, that works! I opened a PR in `homebrew-core` to upgrade `quotatool` with those changes.

Thank you! If that fails for some reason, please get back here and we will solve it some other way. I suspect I always had coreutils installed when developing the macos port, and therefore never ran in to the install issue.
