### ISSUE TITLE
Setting Quotas for Users home directories

### ISSUE THREAD

**Issue by David0117** [ekenberg/quotatool#25]
I have The Littlest JupyterHub instance running and I would like to set limits to how much space these users can use at each of their respective home directories

I have attempted to run the following command 

sudo quotatool -u jupyter-david -b -q 5G -l 10G /home

But I get the following output

quotatool: Filesystem /home does not exist

What needs to be done so that I can limit the home directories of users?

**Comment by ekenberg** [comment]
Disk quotas operate on the filesystem level and are set per filesystem. It looks like /home is not a separate filesystem on your machine, hence the error message. You might want to read up on disk quotas in general and how to set them up for your specific operating system and version. Resources like https://wiki.archlinux.org/title/disk_quota or https://linuxhint.com/disk_quota_ubuntu/ might be a good starting point, assuming you are running on Linux. 

quotatool fills the role of edquota in the above tutorials, but provides a pure command-line interface as opposed to using an interactive editor.

**Comment by David0117** [comment]
Is there a way to turn /home into a file system after the Ubuntu Server OS
installation?

**Comment by ekenberg** [comment]
Your question is about general systems administration and has nothing to do with quotatool. For this you will need to use your favorite search engine. I did and this was my top result: https://www.howtogeek.com/116742/how-to-create-a-separate-home-partition-after-installing-ubuntu/ 
Good luck!
