### ISSUE TITLE
does not seem to work on MacOs Sonoma.

### ISSUE THREAD

**Issue by pmunin** [ekenberg/quotatool#26]
After installing via homebrew:
> quotatool: command not found

**Comment by ekenberg** [comment]
That sounds to me like a problem with Sonoma and Homebrew, not quotatool. Did you go through trouble shooting (brew update twice, brew doctor etc) for homebrew? https://docs.brew.sh/Troubleshooting

**Comment by pmunin** [comment]
I did updating, and reinstalling it multiple times and tried to install it on 2 different macs - problem presist. It may be issue with Sonoma or Homebrew, but it just says on the hb page that is supports it:

![image](https://github.com/ekenberg/quotatool/assets/7120440/4b8bacc2-ecba-4d0c-b79a-0c0f8d2f9d20)

nevertheless, thank you for sharing and supporting this project

**Comment by ekenberg** [comment]
Thank you @pmunin for looking further into this issue. I am not in charge of the homebrew recipe so unsure what verifications  are done before marking the recipe as supported on the homebrew website. Unfortunately I do not have access to a Mac with Sonoma to investigate myself.

Returning to the error you get `"quotatool: command not found"` - it looks to me as if quotatool is not installed at all, or installed somewhere outside the `$PATH` variable. Could you try something like `brew -vd install quotatool` to get verbose and debug information to see in detail where the binary is installed? Also check your `$PATH` to verify that the install location is indeed in there?

Thank you for helping with this issue, even if it is probably not related to quotatool source code - users will end up here anyway looking for answers.

**Comment by ekenberg** [comment]
@pmunin was there any progress on this? About to close this issue since it's related to homebrew and not quotatool, but if there is a solution I would like to write it here for anyone needing the answer.

**Comment by pmunin** [comment]
sorry didn't have a change to get back to it and won't have that need in nearest future. Feel free to close it

**Comment by ekenberg** [comment]
Looks like a path-problem related to Homebrew, would look into it but do not have access to Sonoma
