### ISSUE TITLE
License query

### ISSUE THREAD

**Issue by spotaws** [ekenberg/quotatool#29]
A quick license question: quotatool is clearly under the GPL license, but it does not appear to specify a version in the code or documentation.

The GPL license text says:

`If the Program specifies a version number of this License which applies to it and "any later version", you have the option of following the terms and conditions either of that version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of this License, you may choose any version ever published by the Free Software
Foundation.`

I want to reflect the license correctly in the Fedora package. It would seem that the license should be GPL-1.0-or-later (the SPDX equivalent of "any version ever published by the Free Software Foundation", but I wanted to ask. If you actually intend for the license to be GPL-2.0-only or GPL-2.0-or-later, would you consider adding a line to the README.md to clarify this?

**Comment by ekenberg** [comment]
Thanks @spotaws for you question! I have no answer, what is your suggestion and would you please show me what to write in the README?

**Comment by spotaws** [comment]
I am unaware of any notable reasons to prefer the ancient (and quickly obsoleted) GPL-1.0.

I might suggest specifying "GPL 2.0 or any later version", as that is likely to cover the majority of cases that end users care about.

To apply this, add phrasing like this to README.md:

This software is available under the terms of the GNU Public License (GPL) 2.0 or any later version.

**Comment by ekenberg** [comment]
Thanks @spotaws, README is updated accordingly and version 1.6.5 released.
