### ISSUE TITLE
Error while detecting kernel quota version: No such file or directory on debian wheezy

### ISSUE THREAD

**Issue by soulsf** [ekenberg/quotatool#9]
Got these error message:

Error while detecting kernel quota version: No such file or directory

Last part of strace when running quotatool:

---

poll([{fd=4, events=POLLIN|POLLPRI}], 1, -1) = 1 ([{fd=4, revents=POLLIN}])
read(4, "0\f\2\1\2e\7\n", 8)            = 8
read(4, "\1\0\4\0\4\0", 6)              = 6
time([1350478913])                      = 1350478913
rt_sigaction(SIGPIPE, {SIG_DFL, [], SA_RESTORER, 0x7f172bff54f0}, NULL, 8) = 0
open("/etc/mtab", O_RDONLY)             = 5
brk(0xb52000)                           = 0xb52000
futex(0x7f172c346f20, FUTEX_WAKE_PRIVATE, 2147483647) = 0
fstat(5, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f172c566000
read(5, "rootfs / rootfs rw 0 0\nsysfs /sy"..., 1024) = 680
close(5)                                = 0
munmap(0x7f172c566000, 4096)            = 0
open("/proc/fs/quota", O_RDONLY)        = -1 ENOENT (No such file or directory)
stat("/proc/sys/fs/quota", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
quotactl(Q_GETFMT|USRQUOTA, "rootfs", 0, 0x7fff71ea346c) = -1 ENOENT (No such file or directory)
write(2, "quotatool: ", 11quotatool: )             = 11
write(2, "Error while detecting kernel quo"..., 70Error while detecting kernel quota version: No such file or directory
) = 70
write(2, "\n", 1
)                       = 1
exit_group(3)                           

---

Command: # quotatool -u someuser -b -l 150MB /
# ls -l /proc/sys/fs/quota/

insgesamt 0
-r--r--r-- 1 root root 0 Okt 17 14:41 allocated_dquots
-r--r--r-- 1 root root 0 Okt 17 14:41 cache_hits
-r--r--r-- 1 root root 0 Okt 17 14:41 drops
-r--r--r-- 1 root root 0 Okt 17 14:41 free_dquots
-r--r--r-- 1 root root 0 Okt 17 14:41 lookups
-r--r--r-- 1 root root 0 Okt 17 14:41 reads
-r--r--r-- 1 root root 0 Okt 17 14:41 syncs
-rw-r--r-- 1 root root 0 Okt 17 14:41 warnings
-r--r--r-- 1 root root 0 Okt 17 14:41 writes
# uname -a

Linux EBBK-SRV 3.2.0-3-amd64 #1 SMP Mon Jul 23 02:45:17 UTC 2012 x86_64 GNU/Linux
# cat /proc/sys/fs/quota/*

20
312251
311663
0
312317
66
26
1
47009
# mount

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=10240k,nr_inodes=2056129,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=1646092k,mode=755)
/dev/disk/by-uuid/cfb767db-caae-47d3-9c87-9372c2f617c1 on / type ext4 (rw,relatime,errors=remount-ro,user_xattr,barrier=1,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /run/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=9998140k)

**Comment by alimirjamali** [comment]
Note for the Raspbian users:
$ uname -a
Linux raspberrypi 3.12.35+ #730 PREEMPT Fri Dec 19 18:31:24 GMT 2014 armv6l GNU/Linux
Version of quotatool provided with Raspbian is old (1.4.12) and has this exact issue.
You can clone, compile and use this git repository to fix the issue.
I filed a bug on Raspbian and asked for a fix.

**Comment by foddrick** [comment]
Old thread, but worth mentioning that I found a workaround by using the device instead of the mount point in the quotatool command line. eg.

quotatool -u server182 -bl "2000 Mb" /dev/sda1

**Comment by lhermann** [comment]
In case others come across this issue on their desperate Google search for answers.

I got exactly this error: ```quotatool: Error while detecting kernel quota version: No such process```

And could solve it by enabling quota like so: ```quotaon /dev/sda1```
